/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/3D/glb/hitogata/hitogata_move.glb -o src/components/models/characters/Player.tsx --types --shadows 
*/

import * as THREE from 'three';
import React from 'react';
import { useGraph } from '@react-three/fiber';
import { useGLTF, useAnimations } from '@react-three/drei';
import { GLTF, SkeletonUtils } from 'three-stdlib';

type ActionName = 'アーマチュアアクション';

interface GLTFAction extends THREE.AnimationClip {
  name: ActionName;
}

type GLTFResult = GLTF & {
  nodes: {
    立方体002: THREE.SkinnedMesh;
    Root: THREE.Bone;
  };
  materials: {
    kuro: THREE.MeshStandardMaterial;
  };
  animations: GLTFAction[];
};

export function Model(props: JSX.IntrinsicElements['group']) {
  // useRef must be initialized; allow null until mounted
  const group = React.useRef<THREE.Group | null>(null);
  const { scene, animations } = useGLTF('/hitogata_move.glb');
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene]);
  // useGraph returns a generic map; cast via unknown to satisfy TS for now
  const { nodes, materials } = useGraph(clone) as unknown as GLTFResult;
  // cast group ref to a looser Object3D ref for useAnimations
  const { actions } = useAnimations(animations, group as React.RefObject<THREE.Object3D>);
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="アーマチュア">
          <primitive object={nodes.Root} />
          <skinnedMesh
            name="立方体002"
            geometry={nodes.立方体002.geometry}
            material={materials.kuro}
            skeleton={nodes.立方体002.skeleton}
          />
        </group>
      </group>
    </group>
  );
}

useGLTF.preload('/hitogata_move.glb');
