/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/3D/glb/stage1/stage.glb -o src/components/models/levels/Stage.tsx --types --shadows 
*/

import * as THREE from 'three';
import React from 'react';
import { useGLTF } from '@react-three/drei';

// Minimal GroupProps shape to avoid relying on module-specific exported types.
export type GroupProps = {
  position?: THREE.Vector3 | [number, number, number] | number;
  rotation?: THREE.Euler | [number, number, number];
  scale?: THREE.Vector3 | [number, number, number] | number;
  children?: React.ReactNode;
  dispose?: unknown;
  [key: string]: unknown;
};
import { GLTF } from 'three-stdlib';

type GLTFAction = THREE.AnimationClip;

type GLTFResult = GLTF & {
  nodes: {
    平面: THREE.Mesh;
    平面031: THREE.Mesh;
    平面032: THREE.Mesh;
    平面035: THREE.Mesh;
    平面036: THREE.Mesh;
    平面037: THREE.Mesh;
    平面039: THREE.Mesh;
    平面040: THREE.Mesh;
    平面041: THREE.Mesh;
    平面049: THREE.Mesh;
    平面050: THREE.Mesh;
    平面002: THREE.Mesh;
    立方体: THREE.Mesh;
    立方体003: THREE.Mesh;
    立方体004: THREE.Mesh;
    立方体005: THREE.Mesh;
    立方体006: THREE.Mesh;
    平面001: THREE.Mesh;
    草: THREE.Mesh;
    円柱: THREE.Mesh;
    円柱_1: THREE.Mesh;
    平面017_1: THREE.Mesh;
    平面017_2: THREE.Mesh;
    平面018_1: THREE.Mesh;
    平面018_2: THREE.Mesh;
    平面019_1: THREE.Mesh;
    平面019_2: THREE.Mesh;
    平面020_1: THREE.Mesh;
    平面020_2: THREE.Mesh;
    平面023_1: THREE.Mesh;
    平面023_2: THREE.Mesh;
    平面024_1: THREE.Mesh;
    平面024_2: THREE.Mesh;
    平面025_1: THREE.Mesh;
    平面025_2: THREE.Mesh;
    平面026_1: THREE.Mesh;
    平面026_2: THREE.Mesh;
    平面031_1: THREE.Mesh;
    平面031_2: THREE.Mesh;
    平面032_1: THREE.Mesh;
    平面032_2: THREE.Mesh;
    平面034_1: THREE.Mesh;
    平面034_2: THREE.Mesh;
    平面035_1: THREE.Mesh;
    平面035_2: THREE.Mesh;
    平面035_3: THREE.Mesh;
    平面037_1: THREE.Mesh;
    平面037_2: THREE.Mesh;
    平面038: THREE.Mesh;
    平面038_1: THREE.Mesh;
    平面038_2: THREE.Mesh;
    平面039_1: THREE.Mesh;
    平面039_2: THREE.Mesh;
    平面040_1: THREE.Mesh;
    平面040_2: THREE.Mesh;
    平面040_3: THREE.Mesh;
    平面041_1: THREE.Mesh;
    平面041_2: THREE.Mesh;
    平面042: THREE.Mesh;
    平面042_1: THREE.Mesh;
    平面042_2: THREE.Mesh;
    平面043_1: THREE.Mesh;
    平面043_2: THREE.Mesh;
    平面044_1: THREE.Mesh;
    平面044_2: THREE.Mesh;
    平面045_1: THREE.Mesh;
    平面045_2: THREE.Mesh;
    平面045_3: THREE.Mesh;
    平面045_4: THREE.Mesh;
    平面045_5: THREE.Mesh;
    平面046_1: THREE.Mesh;
    平面046_2: THREE.Mesh;
    平面046_3: THREE.Mesh;
    平面046_4: THREE.Mesh;
    平面046_5: THREE.Mesh;
    平面047_1: THREE.Mesh;
    平面047_2: THREE.Mesh;
    平面047_3: THREE.Mesh;
    平面047_4: THREE.Mesh;
    平面047_5: THREE.Mesh;
    平面048_1: THREE.Mesh;
    平面048_2: THREE.Mesh;
    平面048_3: THREE.Mesh;
    平面048_4: THREE.Mesh;
    平面048_5: THREE.Mesh;
    平面049_1: THREE.Mesh;
    平面049_2: THREE.Mesh;
    平面049_3: THREE.Mesh;
    平面049_4: THREE.Mesh;
    平面049_5: THREE.Mesh;
    平面050_1: THREE.Mesh;
    平面050_2: THREE.Mesh;
    平面050_3: THREE.Mesh;
    平面050_4: THREE.Mesh;
    平面050_5: THREE.Mesh;
    平面051: THREE.Mesh;
    平面051_1: THREE.Mesh;
    平面051_2: THREE.Mesh;
    平面051_3: THREE.Mesh;
    平面051_4: THREE.Mesh;
    平面052: THREE.Mesh;
    平面052_1: THREE.Mesh;
    平面052_2: THREE.Mesh;
    平面052_3: THREE.Mesh;
    平面052_4: THREE.Mesh;
    平面053: THREE.Mesh;
    平面053_1: THREE.Mesh;
    平面053_2: THREE.Mesh;
    平面053_3: THREE.Mesh;
    平面053_4: THREE.Mesh;
    平面054: THREE.Mesh;
    平面054_1: THREE.Mesh;
    平面054_2: THREE.Mesh;
    平面054_3: THREE.Mesh;
    平面055: THREE.Mesh;
    平面055_1: THREE.Mesh;
    平面055_2: THREE.Mesh;
    平面055_3: THREE.Mesh;
    平面055_4: THREE.Mesh;
    平面056: THREE.Mesh;
    平面056_1: THREE.Mesh;
    平面056_2: THREE.Mesh;
    平面056_3: THREE.Mesh;
    平面056_4: THREE.Mesh;
    平面057: THREE.Mesh;
    平面057_1: THREE.Mesh;
    平面057_2: THREE.Mesh;
    平面057_3: THREE.Mesh;
    平面057_4: THREE.Mesh;
    平面058: THREE.Mesh;
    平面058_1: THREE.Mesh;
    平面058_2: THREE.Mesh;
    平面058_3: THREE.Mesh;
    平面058_4: THREE.Mesh;
    平面059: THREE.Mesh;
    平面059_1: THREE.Mesh;
    平面059_2: THREE.Mesh;
    平面059_3: THREE.Mesh;
    平面059_4: THREE.Mesh;
    平面060: THREE.Mesh;
    平面060_1: THREE.Mesh;
    平面060_2: THREE.Mesh;
    平面060_3: THREE.Mesh;
    平面060_4: THREE.Mesh;
    平面061: THREE.Mesh;
    平面061_1: THREE.Mesh;
    平面061_2: THREE.Mesh;
    平面061_3: THREE.Mesh;
    平面062: THREE.Mesh;
    平面062_1: THREE.Mesh;
    平面062_2: THREE.Mesh;
    平面062_3: THREE.Mesh;
    平面062_4: THREE.Mesh;
    平面064: THREE.Mesh;
    平面064_1: THREE.Mesh;
    平面064_2: THREE.Mesh;
    平面064_3: THREE.Mesh;
    平面066: THREE.Mesh;
    平面066_1: THREE.Mesh;
    平面066_2: THREE.Mesh;
    円柱001: THREE.Mesh;
    円柱001_1: THREE.Mesh;
    円柱002: THREE.Mesh;
    円柱002_1: THREE.Mesh;
    円柱003: THREE.Mesh;
    円柱003_1: THREE.Mesh;
    円柱004: THREE.Mesh;
    円柱004_1: THREE.Mesh;
    円柱005: THREE.Mesh;
    円柱005_1: THREE.Mesh;
    円柱006: THREE.Mesh;
    円柱006_1: THREE.Mesh;
    円柱007: THREE.Mesh;
    円柱007_1: THREE.Mesh;
    平面069: THREE.Mesh;
    平面069_1: THREE.Mesh;
    平面069_2: THREE.Mesh;
    平面069_3: THREE.Mesh;
    平面069_4: THREE.Mesh;
    平面070: THREE.Mesh;
    平面070_1: THREE.Mesh;
    平面070_2: THREE.Mesh;
    平面070_3: THREE.Mesh;
    平面071: THREE.Mesh;
    平面071_1: THREE.Mesh;
    平面071_2: THREE.Mesh;
    平面071_3: THREE.Mesh;
    平面071_4: THREE.Mesh;
    平面081: THREE.Mesh;
    平面081_1: THREE.Mesh;
    平面082: THREE.Mesh;
    平面082_1: THREE.Mesh;
    平面083: THREE.Mesh;
    平面083_1: THREE.Mesh;
    平面083_2: THREE.Mesh;
    平面085: THREE.Mesh;
    平面085_1: THREE.Mesh;
    平面085_2: THREE.Mesh;
    平面085_3: THREE.Mesh;
    平面085_4: THREE.Mesh;
    平面086: THREE.Mesh;
    平面086_1: THREE.Mesh;
    平面086_2: THREE.Mesh;
    平面086_3: THREE.Mesh;
    平面086_4: THREE.Mesh;
    平面087: THREE.Mesh;
    平面087_1: THREE.Mesh;
    平面088: THREE.Mesh;
    平面088_1: THREE.Mesh;
    平面089: THREE.Mesh;
    平面089_1: THREE.Mesh;
    平面089_2: THREE.Mesh;
    平面089_3: THREE.Mesh;
    平面090: THREE.Mesh;
    平面090_1: THREE.Mesh;
    平面090_2: THREE.Mesh;
    平面090_3: THREE.Mesh;
    平面090_4: THREE.Mesh;
    平面091: THREE.Mesh;
    平面091_1: THREE.Mesh;
    平面091_2: THREE.Mesh;
    平面091_3: THREE.Mesh;
    平面092: THREE.Mesh;
    平面092_1: THREE.Mesh;
    平面092_2: THREE.Mesh;
    平面092_3: THREE.Mesh;
    平面092_4: THREE.Mesh;
    平面095: THREE.Mesh;
    平面095_1: THREE.Mesh;
    平面096: THREE.Mesh;
    平面096_1: THREE.Mesh;
    平面097: THREE.Mesh;
    平面097_1: THREE.Mesh;
    平面098: THREE.Mesh;
    平面098_1: THREE.Mesh;
    平面100: THREE.Mesh;
    平面100_1: THREE.Mesh;
    平面100_2: THREE.Mesh;
    平面101: THREE.Mesh;
    平面101_1: THREE.Mesh;
    平面101_2: THREE.Mesh;
    平面102: THREE.Mesh;
    平面102_1: THREE.Mesh;
    立方体002: THREE.Mesh;
  };
  materials: {
    tile1: THREE.MeshStandardMaterial;
    ['tile1.001']: THREE.MeshStandardMaterial;
    happa: THREE.MeshStandardMaterial;
    ki: THREE.MeshStandardMaterial;
    ['マテリアル.007']: THREE.MeshStandardMaterial;
    ['hakusenn ']: THREE.MeshStandardMaterial;
    ['マテリアル.008']: THREE.MeshStandardMaterial;
    ['マテリアル.010']: THREE.MeshStandardMaterial;
    tile3: THREE.MeshStandardMaterial;
    kabe1: THREE.MeshStandardMaterial;
    ['マテリアル.003']: THREE.MeshStandardMaterial;
    ['マテリアル.002']: THREE.MeshStandardMaterial;
    ['マテリアル.001']: THREE.MeshStandardMaterial;
    door1: THREE.MeshStandardMaterial;
    ['マテリアル.005']: THREE.MeshStandardMaterial;
    ['マテリアル.004']: THREE.MeshStandardMaterial;
    ['マテリアル.006']: THREE.MeshStandardMaterial;
  };
  animations: GLTFAction[];
};

export function Model(props: GroupProps) {
  const { nodes, materials } = useGLTF('/models/3D/glb/stage1/stage.glb') as unknown as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.平面.geometry}
        material={materials.tile1}
        position={[-35, 0, 35]}
        scale={[5, 1, 5]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.平面031.geometry}
        material={materials['tile1.001']}
        position={[-90, 0, 15]}
        scale={[5, 1, 5]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.平面032.geometry}
        material={materials['tile1.001']}
        position={[-100, 0, 15]}
        scale={[5, 1, 5]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.平面035.geometry}
        material={materials['tile1.001']}
        position={[-15, 0, 60]}
        scale={[14.931, 2.986, 14.931]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.平面036.geometry}
        material={materials['tile1.001']}
        position={[-15, 0, 60]}
        scale={[5, 1, 5]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.平面037.geometry}
        material={materials['tile1.001']}
        position={[-10, 0, 114]}
        rotation={[0, Math.PI / 2, 0]}
        scale={[6.544, 1.309, 6.544]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.平面039.geometry}
        material={materials['tile1.001']}
        position={[-55, 0, 104]}
        rotation={[0, Math.PI / 2, 0]}
        scale={[5, 1, 5]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.平面040.geometry}
        material={materials['tile1.001']}
        position={[-105, 0, 60]}
        scale={[5, 1, 5]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.平面041.geometry}
        material={materials['tile1.001']}
        position={[-10, 0, 15]}
        rotation={[0, Math.PI / 2, 0]}
        scale={[10.161, 2.032, 10.702]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.平面049.geometry}
        material={materials['tile1.001']}
        position={[19.288, 0, -34.293]}
        rotation={[0, Math.PI / 2, 0]}
        scale={[5, 1, 5]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.平面050.geometry}
        material={materials['tile1.001']}
        position={[19.288, 0, -34.293]}
        rotation={[0, Math.PI / 2, 0]}
        scale={[5, 1, 5]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.平面002.geometry}
        material={materials.tile1}
        position={[9, 0, 35]}
        scale={[5, 1, 5]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.立方体.geometry}
        material={nodes.立方体.material}
        position={[-37.75, 0, -40]}
        scale={[68.057, 0.972, 0.972]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.立方体003.geometry}
        material={nodes.立方体003.material}
        position={[-37.75, 0, -40]}
        scale={[68.057, 0.972, 0.972]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.立方体004.geometry}
        material={nodes.立方体004.material}
        position={[-37.75, 0, 109]}
        scale={[68.057, 0.972, 0.972]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.立方体005.geometry}
        material={nodes.立方体005.material}
        position={[-105.75, 0, 40]}
        rotation={[0, Math.PI / 2, 0]}
        scale={[68.057, 0.972, 0.972]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.立方体006.geometry}
        material={nodes.立方体006.material}
        position={[30.25, 0, 40]}
        rotation={[0, Math.PI / 2, 0]}
        scale={[68.057, 0.972, 0.972]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.平面001.geometry}
        material={nodes.平面001.material}
        scale={[40, 1, 40]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.草.geometry}
        material={materials.happa}
        position={[-80, 0, 5]}
        scale={[5, 1, 5]}
      />
      <group position={[-67, 1, 1]} rotation={[Math.PI, -1.194, Math.PI]}>
        <mesh castShadow receiveShadow geometry={nodes.円柱.geometry} material={materials.ki} />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.円柱_1.geometry}
          material={materials['マテリアル.007']}
        />
      </group>
      <group position={[-25, 0, 35]} rotation={[0, Math.PI / 2, 0]} scale={[1.25, 1, 1.25]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.平面017_1.geometry}
          material={materials.tile1}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.平面017_2.geometry}
          material={materials['hakusenn ']}
        />
      </group>
      <group position={[-35, 0, 45]} rotation={[Math.PI, 0, Math.PI]} scale={[1.25, 1, 1.25]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.平面018_1.geometry}
          material={materials.tile1}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.平面018_2.geometry}
          material={materials['hakusenn ']}
        />
      </group>
      <group position={[-45, 0, 35]} rotation={[0, Math.PI / 2, 0]} scale={[1.25, 1, 1.25]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.平面019_1.geometry}
          material={materials.tile1}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.平面019_2.geometry}
          material={materials['hakusenn ']}
        />
      </group>
      <group position={[-35, 0, 25]} rotation={[Math.PI, 0, Math.PI]} scale={[1.25, 1, 1.25]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.平面020_1.geometry}
          material={materials.tile1}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.平面020_2.geometry}
          material={materials['hakusenn ']}
        />
      </group>
      <group position={[-45, 0, 34.5]} scale={[1.25, 1, 1.25]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.平面023_1.geometry}
          material={materials['マテリアル.008']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.平面023_2.geometry}
          material={materials['tile1.001']}
        />
      </group>
      <group position={[-45, 0, 14.5]} scale={[1.25, 1, 1.25]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.平面024_1.geometry}
          material={materials['マテリアル.008']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.平面024_2.geometry}
          material={materials['tile1.001']}
        />
      </group>
      <group position={[-25, 0, 34.5]} scale={[1.25, 1, 1.25]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.平面025_1.geometry}
          material={materials['マテリアル.008']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.平面025_2.geometry}
          material={materials['tile1.001']}
        />
      </group>
      <group position={[-25, 0, 14.5]} scale={[1.25, 1, 1.25]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.平面026_1.geometry}
          material={materials['マテリアル.008']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.平面026_2.geometry}
          material={materials['tile1.001']}
        />
      </group>
      <group position={[-105, 0, 35]} scale={[1.25, 1, 1.25]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.平面031_1.geometry}
          material={materials.tile1}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.平面031_2.geometry}
          material={materials['hakusenn ']}
        />
      </group>
      <group position={[-15, 0, 35]} scale={[1.594, 1, 1.25]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.平面032_1.geometry}
          material={materials.tile1}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.平面032_2.geometry}
          material={materials['hakusenn ']}
        />
      </group>
      <group position={[-35, 0, 15]} rotation={[0, Math.PI / 2, 0]} scale={[1.25, 1, 1.25]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.平面034_1.geometry}
          material={materials.tile1}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.平面034_2.geometry}
          material={materials['hakusenn ']}
        />
      </group>
      <group position={[-14.98, 0, 29]} rotation={[0, Math.PI / 2, 0]} scale={[1.002, 1, 1.25]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.平面035_1.geometry}
          material={materials['マテリアル.010']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.平面035_2.geometry}
          material={materials['tile1.001']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.平面035_3.geometry}
          material={materials.tile3}
        />
      </group>
      <group position={[-35, 0, 105]} rotation={[0, Math.PI / 2, 0]} scale={[1.25, 1, 1.25]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.平面037_1.geometry}
          material={materials.tile1}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.平面037_2.geometry}
          material={materials['hakusenn ']}
        />
      </group>
      <group position={[-104.98, 0, 29]} rotation={[0, Math.PI / 2, 0]} scale={[1.002, 1, 1.25]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.平面038.geometry}
          material={materials['マテリアル.010']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.平面038_1.geometry}
          material={materials['tile1.001']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.平面038_2.geometry}
          material={materials.tile3}
        />
      </group>
      <group position={[-105, 0, 9.5]} scale={[1.25, 1, 1.25]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.平面039_1.geometry}
          material={materials['マテリアル.008']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.平面039_2.geometry}
          material={materials['tile1.001']}
        />
      </group>
      <group
        position={[-41.24, 0, 15.24]}
        rotation={[Math.PI, 0, Math.PI]}
        scale={[1.002, 1, 1.25]}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.平面040_1.geometry}
          material={materials['マテリアル.010']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.平面040_2.geometry}
          material={materials['tile1.001']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.平面040_3.geometry}
          material={materials.tile3}
        />
      </group>
      <group position={[-60.74, 0, 15.26]} rotation={[0, Math.PI / 2, 0]} scale={[1.25, 1, 1.25]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.平面041_1.geometry}
          material={materials['マテリアル.008']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.平面041_2.geometry}
          material={materials['tile1.001']}
        />
      </group>
      <group
        position={[-41.24, 0, 104.24]}
        rotation={[Math.PI, 0, Math.PI]}
        scale={[1.002, 1, 1.25]}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.平面042.geometry}
          material={materials['マテリアル.010']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.平面042_1.geometry}
          material={materials['tile1.001']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.平面042_2.geometry}
          material={materials.tile3}
        />
      </group>
      <group position={[-60.74, 0, 104.26]} rotation={[0, Math.PI / 2, 0]} scale={[1.25, 1, 1.25]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.平面043_1.geometry}
          material={materials['マテリアル.008']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.平面043_2.geometry}
          material={materials['tile1.001']}
        />
      </group>
      <group position={[-60.74, 0, 104.26]} rotation={[0, Math.PI / 2, 0]} scale={[1.25, 1, 1.25]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.平面044_1.geometry}
          material={materials['マテリアル.008']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.平面044_2.geometry}
          material={materials['tile1.001']}
        />
      </group>
      <group position={[-15.837, -0.272, 59.747]} scale={[4.556, 1.272, 4.556]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.平面045_1.geometry}
          material={materials.kabe1}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.平面045_2.geometry}
          material={materials['マテリアル.003']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.平面045_3.geometry}
          material={materials['マテリアル.002']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.平面045_4.geometry}
          material={materials['マテリアル.001']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.平面045_5.geometry}
          material={materials.door1}
        />
      </group>
      <group position={[-15.837, -0.272, 94.747]} scale={[4.556, 1.272, 4.556]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.平面046_1.geometry}
          material={materials.kabe1}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.平面046_2.geometry}
          material={materials['マテリアル.003']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.平面046_3.geometry}
          material={materials['マテリアル.002']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.平面046_4.geometry}
          material={materials['マテリアル.001']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.平面046_5.geometry}
          material={materials.door1}
        />
      </group>
      <group position={[-15.556, -0.272, 70.949]} scale={[4.556, 1.272, 4.556]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.平面047_1.geometry}
          material={materials.kabe1}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.平面047_2.geometry}
          material={materials['マテリアル.003']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.平面047_3.geometry}
          material={materials['マテリアル.005']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.平面047_4.geometry}
          material={materials['マテリアル.001']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.平面047_5.geometry}
          material={materials.door1}
        />
      </group>
      <group position={[-15.837, -0.272, 83.186]} scale={[4.556, 1.272, 4.556]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.平面048_1.geometry}
          material={materials['マテリアル.004']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.平面048_2.geometry}
          material={materials['マテリアル.001']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.平面048_3.geometry}
          material={materials.door1}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.平面048_4.geometry}
          material={materials.kabe1}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.平面048_5.geometry}
          material={materials['マテリアル.003']}
        />
      </group>
      <group
        position={[-54.556, -0.272, 61.949]}
        rotation={[-Math.PI, 0, -Math.PI]}
        scale={[4.556, 1.272, 4.556]}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.平面049_1.geometry}
          material={materials.kabe1}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.平面049_2.geometry}
          material={materials['マテリアル.003']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.平面049_3.geometry}
          material={materials['マテリアル.005']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.平面049_4.geometry}
          material={materials['マテリアル.001']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.平面049_5.geometry}
          material={materials.door1}
        />
      </group>
      <group
        position={[-54.556, -0.272, 86.949]}
        rotation={[-Math.PI, 0, -Math.PI]}
        scale={[4.556, 1.272, 4.556]}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.平面050_1.geometry}
          material={materials.kabe1}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.平面050_2.geometry}
          material={materials['マテリアル.003']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.平面050_3.geometry}
          material={materials['マテリアル.005']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.平面050_4.geometry}
          material={materials['マテリアル.001']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.平面050_5.geometry}
          material={materials.door1}
        />
      </group>
      <group
        position={[-54.837, -0.272, 74.186]}
        rotation={[Math.PI, 0, Math.PI]}
        scale={[4.556, 1.272, 4.556]}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.平面051.geometry}
          material={materials['マテリアル.004']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.平面051_1.geometry}
          material={materials['マテリアル.001']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.平面051_2.geometry}
          material={materials.door1}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.平面051_3.geometry}
          material={materials.kabe1}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.平面051_4.geometry}
          material={materials['マテリアル.003']}
        />
      </group>
      <group
        position={[-50.933, 6.088, 99.325]}
        rotation={[Math.PI, 0, Math.PI]}
        scale={[4.639, 5.014, 4.639]}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.平面052.geometry}
          material={materials['マテリアル.006']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.平面052_1.geometry}
          material={materials['マテリアル.001']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.平面052_2.geometry}
          material={materials.door1}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.平面052_3.geometry}
          material={materials.kabe1}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.平面052_4.geometry}
          material={materials['マテリアル.003']}
        />
      </group>
      <group
        position={[-62.933, 6.088, 49.325]}
        rotation={[0, -Math.PI / 2, 0]}
        scale={[4.639, 5.014, 4.639]}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.平面053.geometry}
          material={materials['マテリアル.006']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.平面053_1.geometry}
          material={materials['マテリアル.001']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.平面053_2.geometry}
          material={materials.door1}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.平面053_3.geometry}
          material={materials.kabe1}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.平面053_4.geometry}
          material={materials['マテリアル.003']}
        />
      </group>
      <group
        position={[-75.837, -0.272, 53.186]}
        rotation={[0, -1.571, 0]}
        scale={[4.556, 1.272, 4.556]}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.平面054.geometry}
          material={materials.happa}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.平面054_1.geometry}
          material={materials['マテリアル.001']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.平面054_2.geometry}
          material={materials.door1}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.平面054_3.geometry}
          material={materials.kabe1}
        />
      </group>
      <group
        position={[-50.837, -0.272, 53.186]}
        rotation={[0, -Math.PI / 2, 0]}
        scale={[4.556, 1.272, 4.556]}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.平面055.geometry}
          material={materials['マテリアル.004']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.平面055_1.geometry}
          material={materials['マテリアル.001']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.平面055_2.geometry}
          material={materials.door1}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.平面055_3.geometry}
          material={materials.kabe1}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.平面055_4.geometry}
          material={materials['マテリアル.003']}
        />
      </group>
      <group
        position={[-99.933, 6.088, 49.325]}
        rotation={[0, -Math.PI / 2, 0]}
        scale={[4.639, 5.014, 4.639]}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.平面056.geometry}
          material={materials['マテリアル.006']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.平面056_1.geometry}
          material={materials['マテリアル.001']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.平面056_2.geometry}
          material={materials.door1}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.平面056_3.geometry}
          material={materials.kabe1}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.平面056_4.geometry}
          material={materials['マテリアル.003']}
        />
      </group>
      <group position={[-15.837, -0.272, 94.747]} scale={[4.556, 1.272, 4.556]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.平面057.geometry}
          material={materials.kabe1}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.平面057_1.geometry}
          material={materials['マテリアル.003']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.平面057_2.geometry}
          material={materials['マテリアル.002']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.平面057_3.geometry}
          material={materials['マテリアル.001']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.平面057_4.geometry}
          material={materials.door1}
        />
      </group>
      <group position={[-15.837, -0.272, -33.253]} scale={[4.556, 1.272, 4.556]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.平面058.geometry}
          material={materials.kabe1}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.平面058_1.geometry}
          material={materials['マテリアル.003']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.平面058_2.geometry}
          material={materials['マテリアル.002']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.平面058_3.geometry}
          material={materials['マテリアル.001']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.平面058_4.geometry}
          material={materials.door1}
        />
      </group>
      <group position={[-15.837, -0.272, 1.747]} scale={[4.556, 1.272, 4.556]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.平面059.geometry}
          material={materials.kabe1}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.平面059_1.geometry}
          material={materials['マテリアル.003']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.平面059_2.geometry}
          material={materials['マテリアル.002']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.平面059_3.geometry}
          material={materials['マテリアル.001']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.平面059_4.geometry}
          material={materials.door1}
        />
      </group>
      <group position={[-15.556, -0.272, -22.051]} scale={[4.556, 1.272, 4.556]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.平面060.geometry}
          material={materials.kabe1}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.平面060_1.geometry}
          material={materials['マテリアル.003']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.平面060_2.geometry}
          material={materials['マテリアル.005']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.平面060_3.geometry}
          material={materials['マテリアル.001']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.平面060_4.geometry}
          material={materials.door1}
        />
      </group>
      <group
        position={[-53.931, -0.272, 2.732]}
        rotation={[Math.PI, 0, Math.PI]}
        scale={[4.556, 1.272, 4.556]}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.平面061.geometry}
          material={materials.happa}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.平面061_1.geometry}
          material={materials['マテリアル.001']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.平面061_2.geometry}
          material={materials.door1}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.平面061_3.geometry}
          material={materials.kabe1}
        />
      </group>
      <group
        position={[-53.931, -0.272, -9.268]}
        rotation={[Math.PI, 0, Math.PI]}
        scale={[4.556, 1.272, 4.556]}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.平面062.geometry}
          material={materials['マテリアル.004']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.平面062_1.geometry}
          material={materials['マテリアル.001']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.平面062_2.geometry}
          material={materials.door1}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.平面062_3.geometry}
          material={materials.kabe1}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.平面062_4.geometry}
          material={materials['マテリアル.003']}
        />
      </group>
      <group
        position={[-53.931, -0.272, -21.268]}
        rotation={[Math.PI, 0, Math.PI]}
        scale={[4.556, 1.272, 4.556]}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.平面064.geometry}
          material={materials.happa}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.平面064_1.geometry}
          material={materials['マテリアル.001']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.平面064_2.geometry}
          material={materials.door1}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.平面064_3.geometry}
          material={materials.kabe1}
        />
      </group>
      <group position={[-59.98, 0, 11]} rotation={[0, -Math.PI / 2, 0]} scale={[1.002, 1, 1.25]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.平面066.geometry}
          material={materials['マテリアル.010']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.平面066_1.geometry}
          material={materials['tile1.001']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.平面066_2.geometry}
          material={materials.tile3}
        />
      </group>
      <group position={[-67, 1, -5]} rotation={[0, -0.75, 0]}>
        <mesh castShadow receiveShadow geometry={nodes.円柱001.geometry} material={materials.ki} />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.円柱001_1.geometry}
          material={materials['マテリアル.007']}
        />
      </group>
      <group position={[-61, 1, -1]} rotation={[0, -1.336, 0]}>
        <mesh castShadow receiveShadow geometry={nodes.円柱002.geometry} material={materials.ki} />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.円柱002_1.geometry}
          material={materials['マテリアル.007']}
        />
      </group>
      <group position={[-93, 1, -1]} rotation={[0, -1.336, 0]}>
        <mesh castShadow receiveShadow geometry={nodes.円柱003.geometry} material={materials.ki} />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.円柱003_1.geometry}
          material={materials['マテリアル.007']}
        />
      </group>
      <group position={[-101, 1, -1]} rotation={[0, 0.09, 0]}>
        <mesh castShadow receiveShadow geometry={nodes.円柱004.geometry} material={materials.ki} />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.円柱004_1.geometry}
          material={materials['マテリアル.007']}
        />
      </group>
      <group position={[-93, 1, -17]} rotation={[0, 0.09, 0]}>
        <mesh castShadow receiveShadow geometry={nodes.円柱005.geometry} material={materials.ki} />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.円柱005_1.geometry}
          material={materials['マテリアル.007']}
        />
      </group>
      <group position={[-65, 1, -24]} rotation={[-Math.PI, 0.011, -Math.PI]}>
        <mesh castShadow receiveShadow geometry={nodes.円柱006.geometry} material={materials.ki} />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.円柱006_1.geometry}
          material={materials['マテリアル.007']}
        />
      </group>
      <group position={[-97, 1, -32]} rotation={[-Math.PI, 0.281, -Math.PI]}>
        <mesh castShadow receiveShadow geometry={nodes.円柱007.geometry} material={materials.ki} />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.円柱007_1.geometry}
          material={materials['マテリアル.007']}
        />
      </group>
      <group
        position={[11.067, 6.088, 50.325]}
        rotation={[0, -Math.PI / 2, 0]}
        scale={[4.639, 5.014, 4.639]}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.平面069.geometry}
          material={materials['マテリアル.006']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.平面069_1.geometry}
          material={materials['マテリアル.001']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.平面069_2.geometry}
          material={materials.door1}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.平面069_3.geometry}
          material={materials.kabe1}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.平面069_4.geometry}
          material={materials['マテリアル.003']}
        />
      </group>
      <group
        position={[-1.837, -0.272, 54.186]}
        rotation={[0, -1.571, 0]}
        scale={[4.556, 1.272, 4.556]}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.平面070.geometry}
          material={materials.happa}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.平面070_1.geometry}
          material={materials['マテリアル.001']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.平面070_2.geometry}
          material={materials.door1}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.平面070_3.geometry}
          material={materials.kabe1}
        />
      </group>
      <group
        position={[23.163, -0.272, 54.186]}
        rotation={[0, -Math.PI / 2, 0]}
        scale={[4.556, 1.272, 4.556]}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.平面071.geometry}
          material={materials['マテリアル.004']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.平面071_1.geometry}
          material={materials['マテリアル.001']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.平面071_2.geometry}
          material={materials.door1}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.平面071_3.geometry}
          material={materials.kabe1}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.平面071_4.geometry}
          material={materials['マテリアル.003']}
        />
      </group>
      <group position={[20, 0, 23.5]} scale={[8.029, 6.423, 8.029]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.平面081.geometry}
          material={materials['マテリアル.008']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.平面081_1.geometry}
          material={materials['tile1.001']}
        />
      </group>
      <group position={[9.288, 0, 15.707]} rotation={[0, Math.PI / 2, 0]} scale={[1.25, 1, 1.25]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.平面082.geometry}
          material={materials.tile1}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.平面082_1.geometry}
          material={materials['hakusenn ']}
        />
      </group>
      <group
        position={[3.288, 0, 15.687]}
        rotation={[Math.PI, 0, Math.PI]}
        scale={[1.002, 1, 1.25]}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.平面083.geometry}
          material={materials['マテリアル.010']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.平面083_1.geometry}
          material={materials['tile1.001']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.平面083_2.geometry}
          material={materials.tile3}
        />
      </group>
      <group
        position={[-9.526, -0.272, 13.544]}
        rotation={[Math.PI, 0, Math.PI]}
        scale={[4.556, 1.272, 4.556]}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.平面085.geometry}
          material={materials['マテリアル.004']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.平面085_1.geometry}
          material={materials['マテリアル.001']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.平面085_2.geometry}
          material={materials.door1}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.平面085_3.geometry}
          material={materials.kabe1}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.平面085_4.geometry}
          material={materials['マテリアル.003']}
        />
      </group>
      <group
        position={[-6.245, 6.088, -21.36]}
        rotation={[Math.PI, 0, Math.PI]}
        scale={[4.639, 5.014, 4.639]}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.平面086.geometry}
          material={materials['マテリアル.006']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.平面086_1.geometry}
          material={materials['マテリアル.001']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.平面086_2.geometry}
          material={materials.door1}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.平面086_3.geometry}
          material={materials.kabe1}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.平面086_4.geometry}
          material={materials['マテリアル.003']}
        />
      </group>
      <group
        position={[9.288, 0, -34.293]}
        rotation={[Math.PI, 0, Math.PI]}
        scale={[1.25, 1, 1.25]}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.平面087.geometry}
          material={materials.tile1}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.平面087_1.geometry}
          material={materials['hakusenn ']}
        />
      </group>
      <group position={[-16.212, 0, 25.707]} rotation={[0, Math.PI / 2, 0]} scale={[1.25, 1, 1.25]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.平面088.geometry}
          material={materials['マテリアル.008']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.平面088_1.geometry}
          material={materials['tile1.001']}
        />
      </group>
      <group
        position={[-9.526, -0.272, 1.544]}
        rotation={[Math.PI, 0, Math.PI]}
        scale={[4.556, 1.272, 4.556]}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.平面089.geometry}
          material={materials.happa}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.平面089_1.geometry}
          material={materials['マテリアル.001']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.平面089_2.geometry}
          material={materials.door1}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.平面089_3.geometry}
          material={materials.kabe1}
        />
      </group>
      <group position={[24.613, 6.088, 0.64]} scale={[4.639, 5.014, 4.639]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.平面090.geometry}
          material={materials['マテリアル.006']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.平面090_1.geometry}
          material={materials['マテリアル.001']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.平面090_2.geometry}
          material={materials.door1}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.平面090_3.geometry}
          material={materials.kabe1}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.平面090_4.geometry}
          material={materials['マテリアル.003']}
        />
      </group>
      <group position={[28.474, -0.272, 13.544]} scale={[4.556, 1.272, 4.556]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.平面091.geometry}
          material={materials.happa}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.平面091_1.geometry}
          material={materials['マテリアル.001']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.平面091_2.geometry}
          material={materials.door1}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.平面091_3.geometry}
          material={materials.kabe1}
        />
      </group>
      <group position={[28.474, -0.272, -11.456]} scale={[4.556, 1.272, 4.556]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.平面092.geometry}
          material={materials['マテリアル.004']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.平面092_1.geometry}
          material={materials['マテリアル.001']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.平面092_2.geometry}
          material={materials.door1}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.平面092_3.geometry}
          material={materials.kabe1}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.平面092_4.geometry}
          material={materials['マテリアル.003']}
        />
      </group>
      <group position={[9, 0, 25]} rotation={[Math.PI, 0, Math.PI]} scale={[1.25, 1, 1.25]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.平面095.geometry}
          material={materials.tile1}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.平面095_1.geometry}
          material={materials['hakusenn ']}
        />
      </group>
      <group position={[-1, 0, 14.5]} scale={[1.25, 1, 1.25]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.平面096.geometry}
          material={materials['マテリアル.008']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.平面096_1.geometry}
          material={materials['tile1.001']}
        />
      </group>
      <group position={[19, 0, 14.5]} scale={[1.25, 1, 1.25]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.平面097.geometry}
          material={materials['マテリアル.008']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.平面097_1.geometry}
          material={materials['tile1.001']}
        />
      </group>
      <group position={[19, 0, 35]} scale={[1.25, 1, 1.25]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.平面098.geometry}
          material={materials.tile1}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.平面098_1.geometry}
          material={materials['hakusenn ']}
        />
      </group>
      <group position={[20.02, 0, 41]} rotation={[0, -Math.PI / 2, 0]} scale={[1.002, 1, 1.25]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.平面100.geometry}
          material={materials['マテリアル.010']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.平面100_1.geometry}
          material={materials['tile1.001']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.平面100_2.geometry}
          material={materials.tile3}
        />
      </group>
      <group position={[50.02, 0, 41]} rotation={[0, -Math.PI / 2, 0]} scale={[1.002, 1, 1.25]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.平面101.geometry}
          material={materials['マテリアル.010']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.平面101_1.geometry}
          material={materials['tile1.001']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.平面101_2.geometry}
          material={materials.tile3}
        />
      </group>
      <group position={[-90, 0, 23.5]} scale={[8.029, 6.423, 8.029]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.平面102.geometry}
          material={materials['マテリアル.008']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.平面102_1.geometry}
          material={materials['tile1.001']}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.立方体002.geometry}
        material={nodes.立方体002.material}
        position={[0, 0, -8]}
        rotation={[0, Math.PI / 2, 0]}
        scale={0.451}
      />
    </group>
  );
}

useGLTF.preload('/models/3D/glb/stage1/stage.glb');
