/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/3D/glb/stage1/stage1.glb -o src/components/models/levels/Stage1.tsx --types --shadows 
*/

import * as THREE from 'three';
import React from 'react';
import { useGLTF } from '@react-three/drei';

// Minimal GroupProps shape to avoid relying on module-specific exported types.
export type GroupProps = {
  position?: THREE.Vector3 | [number, number, number] | number;
  rotation?: THREE.Euler | [number, number, number];
  scale?: THREE.Vector3 | [number, number, number] | number;
  children?: React.ReactNode;
  dispose?: unknown;
  [key: string]: unknown;
};
import { GLTF } from 'three-stdlib';

type GLTFAction = THREE.AnimationClip;

type GLTFResult = GLTF & {
  nodes: {
    平面: THREE.Mesh;
    平面001: THREE.Mesh;
    平面004: THREE.Mesh;
    平面006: THREE.Mesh;
    平面007: THREE.Mesh;
    平面018: THREE.Mesh;
    平面019: THREE.Mesh;
    平面022: THREE.Mesh;
    平面024: THREE.Mesh;
    平面026: THREE.Mesh;
    平面027: THREE.Mesh;
    平面028: THREE.Mesh;
    平面029: THREE.Mesh;
    平面035: THREE.Mesh;
    平面011: THREE.Mesh;
    立方体: THREE.Mesh;
    立方体001: THREE.Mesh;
    立方体002: THREE.Mesh;
    立方体003: THREE.Mesh;
    立方体004: THREE.Mesh;
    立方体005: THREE.Mesh;
    平面002: THREE.Mesh;
  };
  materials: {
    kabe: THREE.MeshStandardMaterial;
    yuka: THREE.MeshStandardMaterial;
  };
  animations: GLTFAction[];
};

export function Model(props: GroupProps) {
  const { nodes, materials } = useGLTF('/models/3D/glb/stage1/stage1.glb') as unknown as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.平面.geometry}
        material={materials.kabe}
        scale={[10, 1, 10]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.平面001.geometry}
        material={nodes.平面001.material}
        position={[0.264, 2.704, 0]}
        rotation={[0, 0, -Math.PI / 2]}
        scale={[1, 1, 1.03]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.平面004.geometry}
        material={nodes.平面004.material}
        position={[0.264, 2.704, 0]}
        rotation={[0, 0, -Math.PI / 2]}
        scale={[1, 1, 1.03]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.平面006.geometry}
        material={materials.kabe}
        position={[16.165, 2.704, 20.421]}
        rotation={[-Math.PI / 2, Math.PI / 2, 0]}
        scale={[1, 1, 1.03]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.平面007.geometry}
        material={materials.kabe}
        position={[0.264, 2.704, 0]}
        rotation={[0, 0, -Math.PI / 2]}
        scale={[1, 1, 1.03]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.平面018.geometry}
        material={nodes.平面018.material}
        position={[-0.136, 2.704, 25.518]}
        rotation={[-Math.PI / 2, Math.PI / 2, 0]}
        scale={[1, 1, 1.03]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.平面019.geometry}
        material={nodes.平面019.material}
        position={[0.264, 2.704, 0]}
        rotation={[Math.PI / 2, -Math.PI / 2, 0]}
        scale={[1, 1, 1.03]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.平面022.geometry}
        material={nodes.平面022.material}
        position={[16.165, 2.704, 28.739]}
        rotation={[-Math.PI / 2, Math.PI / 2, 0]}
        scale={[1, 1, 1.03]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.平面024.geometry}
        material={nodes.平面024.material}
        position={[16.165, 2.704, 31.647]}
        rotation={[-Math.PI / 2, Math.PI / 2, 0]}
        scale={[1, 1, 1.03]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.平面026.geometry}
        material={nodes.平面026.material}
        position={[16.165, 2.704, 17.598]}
        rotation={[-Math.PI / 2, Math.PI / 2, 0]}
        scale={[1, 1, 1.03]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.平面027.geometry}
        material={materials.kabe}
        position={[7.572, 2.704, 4.124]}
        rotation={[Math.PI, 0, Math.PI / 2]}
        scale={[1, 1, 1.03]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.平面028.geometry}
        material={nodes.平面028.material}
        position={[0.671, 2.704, 5.918]}
        rotation={[-Math.PI / 2, Math.PI / 2, 0]}
        scale={[1, 1, 1.03]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.平面029.geometry}
        material={nodes.平面029.material}
        position={[-4.186, 2.704, -9.845]}
        rotation={[Math.PI / 2, -Math.PI / 2, 0]}
        scale={[1, 1, 1.03]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.平面035.geometry}
        material={materials.kabe}
        position={[-9.258, 2.704, -12.341]}
        rotation={[0, 0, -Math.PI / 2]}
        scale={[1, 1, 1.03]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.平面011.geometry}
        material={materials.kabe}
        scale={[1.25, 1, 1.25]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.立方体.geometry}
        material={nodes.立方体.material}
        position={[3.729, 0.25, 0.096]}
        scale={[0.25, 0.25, 0.5]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.立方体001.geometry}
        material={nodes.立方体001.material}
        position={[1.493, 0.25, 0]}
        scale={[0.25, 0.25, 0.5]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.立方体002.geometry}
        material={nodes.立方体002.material}
        position={[0, 0.25, 0.926]}
        rotation={[0, Math.PI / 2, 0]}
        scale={[0.25, 0.25, 0.5]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.立方体003.geometry}
        material={nodes.立方体003.material}
        position={[1.659, 0.25, 2.435]}
        rotation={[0, Math.PI / 2, 0]}
        scale={[0.25, 0.25, 0.5]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.立方体004.geometry}
        material={nodes.立方体004.material}
        position={[-4.612, 0.25, 0.485]}
        scale={[0.25, 0.25, 0.5]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.立方体005.geometry}
        material={nodes.立方体005.material}
        position={[-7.76, 0.25, -8.779]}
        scale={[0.25, 0.25, 0.5]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.平面002.geometry}
        material={materials.yuka}
        userData={{ type: 'ground' }}
        scale={[10, 1, 10]}
      />
    </group>
  );
}

useGLTF.preload('/models/3D/glb/stage1/stage1.glb');

export default Model;
